const HTML_TYPE = "text/html; charset=utf-8";

const escapeHtml = (value = "") => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#039;");

const shell = ({ title, body, siteKey = "", script = "" }) => `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="TrailGenic permit availability alerts.">
  <title>${escapeHtml(title)} | TrailGenic</title>
  <style>
    :root { color-scheme: light; --ink:#11251b; --muted:#53635a; --line:#d8e2db; --forest:#176b42; --cream:#f7f8f4; --warning:#fff8e7; }
    * { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--cream); font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
    header, main, footer { width:min(760px, calc(100% - 32px)); margin-inline:auto; } header { padding:28px 0 12px; display:flex; align-items:center; justify-content:space-between; gap:16px; } .brand { color:var(--forest); font-size:1.15rem; font-weight:800; letter-spacing:-.02em; text-decoration:none; } nav { display:flex; gap:14px; font-size:.9rem; } a { color:#0b5d3a; } main { background:#fff; border:1px solid var(--line); border-radius:16px; padding:clamp(22px,5vw,42px); margin:18px auto 32px; box-shadow:0 8px 25px #12331b0d; } h1 { margin:0 0 8px; font-size:clamp(1.8rem,5vw,2.7rem); line-height:1.08; letter-spacing:-.04em; } h2 { margin-top:32px; font-size:1.2rem; } p.lead { color:var(--muted); margin:0 0 28px; font-size:1.05rem; } .notice { background:var(--warning); border:1px solid #efdba6; border-radius:10px; padding:12px 14px; font-size:.91rem; margin:18px 0; } form { display:grid; gap:18px; } label { display:grid; gap:6px; font-size:.92rem; font-weight:650; } input, select, button { font:inherit; } input, select { width:100%; padding:11px 12px; color:var(--ink); border:1px solid #aabbb0; border-radius:8px; background:white; } .fields { display:grid; gap:16px; grid-template-columns:repeat(2,minmax(0,1fr)); } .dates { display:grid; gap:8px; } .date-row { display:grid; grid-template-columns:1fr auto; gap:8px; } button { border:0; border-radius:8px; padding:11px 16px; font-weight:750; cursor:pointer; } button.primary { background:var(--forest); color:white; } button.secondary { background:#eaf1ec; color:var(--ink); } button:disabled { cursor:not-allowed; opacity:.6; } .consent { display:flex; align-items:flex-start; gap:9px; font-weight:400; font-size:.9rem; } .consent input { width:18px; height:18px; margin-top:2px; flex:none; } .status { display:none; border-radius:9px; padding:12px 14px; } .status.show { display:block; } .status.error { background:#fff1f0; color:#8d1a13; } .status.success { background:#edf8f0; color:#155b36; } .hidden { display:none; } .small { color:var(--muted); font-size:.85rem; } footer { color:var(--muted); padding:0 0 36px; font-size:.85rem; } footer a { margin-right:12px; } ul { padding-left:20px; } @media (max-width:560px) { .fields { grid-template-columns:1fr; } header { align-items:flex-start; flex-direction:column; } }
  </style>
</head>
<body>
  <header><a class="brand" href="/">TrailGenic</a><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/help">Help</a></nav></header>
  <main>${body}</main>
  <footer><a href="/privacy">Privacy Policy</a><a href="/terms">Terms &amp; Conditions</a><a href="/help">Help</a></footer>
  ${siteKey ? '<script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" async defer></script>' : ""}
  <script>window.TURNSTILE_SITE_KEY=${JSON.stringify(siteKey)};</script>
  ${script ? `<script>${script}</script>` : ""}
</body></html>`;

const signupScript = `(() => {
  const form = document.querySelector("#alert-form");
  const status = document.querySelector("#status");
  const verify = document.querySelector("#verify");
  const verificationForm = document.querySelector("#verification-form");
  const dates = document.querySelector("#dates");
  let manageToken = sessionStorage.getItem("trailgenic_manage_token") || "";
  let widgetId;
  const show = (message, kind = "error") => { status.textContent = message; status.className = "status show " + kind; };
  const addDate = () => { const row = document.createElement("div"); row.className = "date-row"; row.innerHTML = '<input type="date" required aria-label="Requested permit date"><button class="secondary" type="button" aria-label="Remove date">Remove</button>'; row.querySelector("button").onclick = () => row.remove(); dates.append(row); };
  document.querySelector("#add-date").onclick = addDate;
  const loadPermits = async () => { const response = await fetch("/permits"); const { permits } = await response.json(); const select = form.permit_id; for (const permit of permits) { const option = document.createElement("option"); option.value = permit.id; option.textContent = permit.name + " (up to " + permit.max_party_size + ")"; select.append(option); } };
  const renderTurnstile = () => { if (!window.TURNSTILE_SITE_KEY || typeof window.turnstile?.render !== "function") return; widgetId = window.turnstile.render("#turnstile-widget", { sitekey: window.TURNSTILE_SITE_KEY }); };
  window.onload = () => { loadPermits().catch(() => show("We could not load permit options. Please refresh and try again.")); const wait = setInterval(() => { if (typeof window.turnstile?.render === "function") { clearInterval(wait); renderTurnstile(); } }, 100); };
  form.addEventListener("submit", async (event) => { event.preventDefault(); status.className = "status"; const token = typeof window.turnstile?.getResponse === "function" && widgetId !== undefined ? window.turnstile.getResponse(widgetId) : ""; if (!token) return show("Please complete the human verification."); const payload = { phone: form.phone.value.trim(), permit_id: form.permit_id.value, party_size: Number(form.party_size.value), dates: [...dates.querySelectorAll("input")].map((input) => input.value), consent: form.consent.checked, turnstile_token: token }; const submit = form.querySelector("button[type=submit]"); submit.disabled = true; try { const response = await fetch("/trackers", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to start your alert."); manageToken = body.tracker.manage_token; sessionStorage.setItem("trailgenic_manage_token", manageToken); form.classList.add("hidden"); verify.classList.remove("hidden"); show("We sent a verification code to " + body.tracker.phone_masked + ". Enter it below to activate your alert.", "success"); } catch (error) { show(error.message); if (typeof window.turnstile?.reset === "function") window.turnstile.reset(widgetId); } finally { submit.disabled = false; } });
  verificationForm.addEventListener("submit", async (event) => { event.preventDefault(); try { const response = await fetch("/trackers/verify", { method:"POST", headers:{"Content-Type":"application/json", Authorization:"Bearer " + manageToken}, body:JSON.stringify({ code: verificationForm.code.value.trim() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "That code was not accepted."); verify.innerHTML = '<h2>Your permit alert is active</h2><p>You’ll receive a text only when a requested permit date has enough availability for your selected party size.</p><p class="small">Reply STOP to any alert to opt out. Reply HELP for help.</p>'; show("Phone verified—your alert is active.", "success"); } catch (error) { show(error.message); } });
})();`;

export const publicPage = (pathname, env) => {
  if (pathname === "/") {
    return shell({
      title: "Permit Alerts",
      siteKey: env.TURNSTILE_SITE_KEY || "",
      body: `<h1>Get the permit alert, not the refresh marathon.</h1><p class="lead">TrailGenic watches selected permit dates and texts you when enough inventory opens for your group.</p><div id="status" class="status" role="status" aria-live="polite"></div><form id="alert-form"><div class="fields"><label>Permit<select name="permit_id" required><option value="">Loading permits…</option></select></label><label>Party size<input name="party_size" type="number" min="1" max="15" value="1" required></label></div><div><label>Requested date(s)</label><div id="dates" class="dates"><div class="date-row"><input type="date" required aria-label="Requested permit date"><button class="secondary" type="button" aria-label="Remove date">Remove</button></div></div><button id="add-date" class="secondary" type="button" style="margin-top:8px">Add another date</button></div><label>Mobile number<input name="phone" type="tel" inputmode="tel" placeholder="+15551234567" autocomplete="tel" required><span class="small">Enter a U.S. number in international format, beginning with +1.</span></label><div id="turnstile-widget"></div><label class="consent"><input name="consent" type="checkbox" required>I agree to receive recurring automated TrailGenic Permit Alert SMS messages at this number about my selected permit dates and party size. Consent is not a condition of purchase. Message and data rates may apply. Reply STOP to opt out and HELP for help. See the <a href="/terms" target="_blank">Terms</a> and <a href="/privacy" target="_blank">Privacy Policy</a>.</label><button class="primary" type="submit">Send verification code</button></form><section id="verify" class="hidden"><h2>Verify your phone</h2><p>Enter the code we texted you to activate your alert.</p><form id="verification-form"><label>Verification code<input name="code" inputmode="numeric" autocomplete="one-time-code" required></label><button class="primary" type="submit">Activate alert</button></form></section><p class="notice">Availability is monitored information, not a reservation. TrailGenic does not book permits and cannot guarantee inventory will remain available.</p>`,
      script: signupScript
    });
  }
  if (pathname === "/privacy") return shell({ title: "Privacy Policy", body: `<h1>Privacy Policy</h1><p class="lead">Effective July 19, 2026</p><h2>Information we collect</h2><p>When you request a permit alert, TrailGenic collects your mobile number, selected permit product, requested date or dates, party size, phone-verification status, and basic service records needed to operate the alert.</p><h2>How we use it</h2><p>We use this information to verify your phone, monitor the dates you selected, send availability alerts, prevent abuse, and operate and improve the service. We do not use your number to send unrelated marketing messages through this permit-alert service.</p><h2>Service providers</h2><p>We use Cloudflare to host and protect the service and Twilio to verify phone numbers and deliver SMS. These providers process information only to provide their services to TrailGenic.</p><h2>Retention and choices</h2><p>You can opt out of alert messages by replying STOP. We retain records as reasonably necessary to operate, secure, and comply with our obligations for the service. To ask about your information, use the contact information on <a href="https://www.trailgenic.com/">trailgenic.com</a>.</p><h2>Updates</h2><p>We may update this policy as the service develops. The effective date above reflects the latest version.</p>` });
  if (pathname === "/terms") return shell({ title: "Terms & Conditions", body: `<h1>Permit Alert Terms &amp; Conditions</h1><p class="lead">Effective July 19, 2026</p><h2>What the service does</h2><p>TrailGenic monitors selected permit inventory and sends SMS alerts when availability appears to meet your requested party size. TrailGenic is independent from Recreation.gov and public-land agencies. We do not make reservations and do not guarantee availability, timing, or successful booking.</p><h2>SMS terms</h2><p>By checking the consent box and verifying your phone, you agree to receive recurring automated TrailGenic Permit Alert SMS messages about the permit selections you submit. Message frequency varies based on availability. Message and data rates may apply. Consent is not a condition of purchase.</p><p>Reply <strong>STOP</strong> to any alert to opt out. Reply <strong>HELP</strong> for help or visit <a href="/help">alerts.trailgenic.com/help</a>. Carriers are not liable for delayed or undelivered messages.</p><h2>Your responsibilities</h2><p>Submit only your own phone number, keep your permit preferences accurate, and review availability promptly through the official booking provider. Do not use the service to interfere with booking systems or circumvent agency rules.</p><h2>Changes and contact</h2><p>We may change or discontinue the service. Questions about these terms can be sent through the contact information on <a href="https://www.trailgenic.com/">trailgenic.com</a>.</p>` });
  if (pathname === "/help") return shell({ title: "Help", body: `<h1>Permit Alert Help</h1><p class="lead">Need help with a TrailGenic permit alert?</p><ul><li>Reply <strong>STOP</strong> to an alert to opt out at any time.</li><li>Reply <strong>START</strong> or <strong>UNSTOP</strong> to re-enable messages from the TrailGenic number, then create a new alert for the dates you want monitored.</li><li>Reply <strong>HELP</strong> for automated SMS help.</li><li>For account or service questions, contact TrailGenic using the contact information on <a href="https://www.trailgenic.com/">trailgenic.com</a>.</li></ul><p class="notice">TrailGenic cannot change or book a permit for you. Use the official booking link in your alert to review and reserve available inventory.</p>` });
  return null;
};
